services:
  webapi:
    image: recepgunes/devmatch:master
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire_dashboard:18889
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123.
      POSTGRES_DB: DevMatch
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  aspire_dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    ports:
      - "18888:18888"

volumes:
  postgis_data:
    driver: local
