services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite
    networks:
      - nginx-network
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"

  nginx-gateway:
    image: nginx:latest
    container_name: nginx-gateway
    depends_on:
      - azurite
    networks:
      - nginx-network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    container_name: aspire-dashboard
    networks:
      - nginx-network
    ports:
      - "18888:18888"
      - "4317:18889"

networks:
  nginx-network:
    driver: bridge

volumes:
  azurite-data:
    driver: local
